version: "2.0"

services:
  frontend:
    build: ./docker/node
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:8080/
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/
  backend:
    build: ./docker/node
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/
