version: "2.0"

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: alpha_beta
      POSTGRES_PASSWORD: alpha_beta
      POSTGRES_DB: alpha_beta
    ports:
      - 5432:5432
    volumes:
      - ./alpha_beta_db:/var/lib/postgresql/data
  frontend:
    build: ./docker/node
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/
  backend:
    build: ./docker/node
    environment:
      NODE_ENV: development
      DATABASE_HOST: database
      POSTGRES_USER: alpha_beta
      POSTGRES_PASSWORD: alpha_beta
      POSTGRES_DB: alpha_beta
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/
volumes:
  alpha_beta_db:
