version: 2.1
orbs:
  node: circleci/node@5.0.3
commands:
  deploy:
    parameters:
      service:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet app deploy --appyaml=<<parameters.service>>.yaml
          name: Deploy to GCP App Engine
      - run:
          command: gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service=<<parameters.service>> | tail -n +6 | xargs -r gcloud app versions delete --quiet
          name: Delete app versions beyond 5th version in history
jobs:
  lint-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/frontend
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/frontend
      - persist_to_workspace:
          root: ./frontend
          paths:
            - .
  lint-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/backend
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/backend
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/backend
      - persist_to_workspace:
          root: ./backend
          paths:
            - .
  build-frontend:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm run build
          name: Build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy-frontend:
    docker:
      - image: google/cloud-sdk:460.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet app deploy --appyaml=frontend.yaml
          name: Deploy to GCP App Engine
      - run:
          command: gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" | tail -n +6 | xargs -r gcloud app versions delete --quiet
          name: Delete app versions beyond 5th version in history
  deploy-backend:
    docker:
      - image: google/cloud-sdk:460.0.0
    steps:
      - deploy:
          service: "backend"

workflows:
  frontend:
    jobs:
      - lint-and-test-frontend
      - hold:
          type: approval
          requires:
            - lint-and-test-frontend
          filters:
            branches:
              only:
                - main
      - build-frontend:
          requires:
            - hold
      - deploy-frontend:
          requires:
            - build-frontend
  backend:
    jobs:
      - lint-and-test-backend
      - hold:
          type: approval
          requires:
            - lint-and-test-backend
          filters:
            branches:
              only:
                - main
      - deploy-backend:
          requires:
            - hold
