version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  lint-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/frontend
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/frontend
      - persist_to_workspace:
          root: ./frontend
          paths:
            - .
  build:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm run build
          name: Build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    docker:
      - image: google/cloud-sdk
        auth:
          username: ldverdier
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - run: |
          echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet app deploy

workflows:
  frontend:
    jobs:
      - lint-and-test-frontend
      - build:
          requires:
            - lint-and-test-frontend
      - deploy:
          requires:
            - build
