version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  lint-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/frontend
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/frontend
      - persist_to_workspace:
          root: ./frontend
          paths:
            - .
  build-frontend:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ls
          name: Display list of elements retrieved from workspace
      - run:
          command: npm run build
          name: Build

workflows:
  frontend:
    jobs:
      - lint-and-test-frontend
      - build-frontend:
          requires:
            - lint-and-test-frontend
